name: Ma super CI/CD

#ma CI s'execute au push sur ma branche main
on:
  push:
    branches: [ main ]
    
#les différents jobs
jobs:
  #je donne un nom
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installation des dépendances
        run: npm install

      - name: Lancement des tests unitaires
        run: npm run test

      - name: Build de l'appli
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Deploiement en github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
